import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-5 border-b-2">
          <ul>
            <Link href="/">Home</Link>
          </ul>
          <ul>
            <Link prefetch={false} href="/about">
              about
            </Link>
          </ul>
          <ul>
            <Link href="/blogs">Blog</Link>
          </ul>
               
        </nav>
        {children}
      </body>
    </html>
  );
}
